# Generated by Django 4.2.2 on 2023-07-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('content', models.CharField()),
                ('value', models.BooleanField(default=True)),
                ('view_count', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
