# Generated by Django 4.2.2 on 2023-07-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('phone', models.CharField()),
                ('time', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('massage', models.TextField()),
                ('date', models.CharField()),
                ('message', models.TextField()),
            ],
        ),
    ]
