# Generated by Django 4.2.2 on 2023-07-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('count_view', models.IntegerField()),
                ('show', models.BooleanField(default=True)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
